### ISSUE TITLE
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.

### ISSUE THREAD

**Issue by eGit** [BarrensZeppelin/humanize-gcode#9]
I installed humanize-gcode on Linux Mint 22 using: pipx install humanize-gcode

Executing 'hucode' results in this error:
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

I installed python3-lxml-html-clean on Linux Mint 22. But since humanize-gcode is installed in a seperate environment via pipx, it probably doesn't care about Linux Mint 22 system packages and just uses what is available in its isolated environment.

Can I fix this somehow?

**Comment by BarrensZeppelin** [comment]
I've uploaded a new version that should fix the issue. Thank you for the notification. :slightly_smiling_face:

**Comment by eGit** [comment]
Thanks!

I also tried to get it working by installing "lxml_html_clean" via pipx. But better it works out of the box. Cheers!
